version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$TYPEORM_USERNAME
      - POSTGRES_PASSWORD=$TYPEORM_PASSWORD
    ports:
      - $TYPEORM_PORT:5432
    volumes: 
      - db:/var/lib/postgresql/data
  
  backend-api:
    depends_on:
      - db
    build: ./backend-api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - backend-api
    build:
      context: ./client
      args:
        - VITE_APP_API=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend  

volumes:
  db:
    driver: local

networks:
  backend:
  frontend: